#!/usr/bin/env python3 
import sys
from pymol import cmd

if len(sys.argv) != 2:
    exit( 1 )


cmd.delete('all')
cmd.load(sys.argv[-1])
fh = open('seq.fasta', 'w')
fh.write(cmd.get_fastastr())
fh.close()
cmd.delete('all')
