#!/usr/bin/env python3
import sys
from pymol import cmd

if len(sys.argv) != 2:
    exit( 0 )


cmd.delete('all')
cmd.load(sys.argv[-1])

fh = open('alignment.ali', 'w')
fh.write(cmd.get_fastastr())
fh.close()


cmd.delete('all')
